baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: localhost/example-craft-one
primary: true
siteGroup: 7a9179e3-91ee-4a6f-8549-73951bed032b # localhost/example-craft-one
sortOrder: 1
