columnSuffix: null
contentColumnType: string
fieldGroup: 2b232fb3-8c46-45ba-8cf6-033789dbedf4 # Common
handle: navLinks
instructions: ''
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
