defaultPlacement: end
enableVersioning: true
handle: about
name: 'About Us'
propagationMethod: all
siteSettings:
  60e619f9-0c07-431e-a4ca-ae9599eacea8: # localhost/example-craft-one
    enabledByDefault: true
    hasUrls: true
    template: about.twig
    uriFormat: about
type: single
