defaultPlacement: end
enableVersioning: true
handle: clients
name: Clients
propagationMethod: all
siteSettings:
  60e619f9-0c07-431e-a4ca-ae9599eacea8: # localhost/example-craft-one
    enabledByDefault: true
    hasUrls: true
    template: clients.twig
    uriFormat: clients
type: single
